name: mollet
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^1.0.8
  flutter_svg: ^0.17.1
  firebase_auth: 
  cloud_firestore: ^0.13.4+1
  google_fonts:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/wallet.svg
   - assets/images/home.svg
   - assets/images/clock.svg
   - assets/images/fav.svg
   - assets/images/mail.svg
   - assets/images/settings.svg
   - assets/images/pay.svg
   - assets/images/logout.svg
   - assets/images/femaleAvatar.svg
   - assets/images/gift.svg
   - assets/images/question.svg
   - assets/images/help.svg
   - assets/images/noHistory.svg
   - assets/images/noInbox.svg
   - assets/images/noFavs.svg
   - assets/images/online_shopping.svg
   - assets/images/login.svg
   - assets/images/fingerprint.svg
   - assets/images/verified.svg
   - assets/images/phone_number.svg
   - assets/images/password.svg
   - assets/images/mc_symbol.svg
   - assets/images/visa.svg
   - assets/images/paypal.svg
   - assets/images/pets.svg
   - assets/images/petsitter.svg
   - assets/images/petfood.svg
   - assets/images/vet.svg
   - assets/images/veterinarian.svg
   - assets/images/caretaker.svg
   - assets/images/creditcard.svg
   - assets/images/cardsuccess.svg
   - assets/images/manage.svg
   - assets/images/scan_fingerprint.png
   - assets/images/checkmark.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
